export default [
  {
    id: Math.random(),
    title: "Susce pulvinar metus nulla, vel facilisis sem",
    desc:
      "Lorem ipsum dolor sit amet, consectetur adipisc ing ipsum dolor sit amet, consectetur dolor sit amet, consectetur adipisc ing ipsum dolor sit amet, consectetur elit.",
    imageUrl: require("../../images/review/5.jpg"),
    imageAlt: "1",
    tag1: "#new",
    tag2: "#game",
    tag3: "#adventure",
  },
  {
    id: Math.random(),
    title: "Susce pulvinar metus nulla, vel facilisis sem",
    desc:
      "Lorem ipsum dolor sit amet, consectetur adipisc ing ipsum dolor sit amet, consectetur dolor sit amet, consectetur adipisc ing ipsum dolor sit amet, consectetur elit.",
    imageUrl: require("../../images/review/6.jpg"),
    imageAlt: "1",
    tag1: "#new",
    tag2: "#game",
    tag3: "#adventure",
  },
  {
    id: Math.random(),
    title: "Susce pulvinar metus nulla, vel facilisis sem",
    desc:
      "Lorem ipsum dolor sit amet, consectetur adipisc ing ipsum dolor sit amet, consectetur dolor sit amet, consectetur adipisc ing ipsum dolor sit amet, consectetur elit.",
    imageUrl: require("../../images/review/7.jpg"),
    imageAlt: "1",
    tag1: "#new",
    tag2: "#game",
    tag3: "#adventure",
  },
  {
    id: Math.random(),
    title: "Susce pulvinar metus nulla, vel facilisis sem",
    desc:
      "Lorem ipsum dolor sit amet, consectetur adipisc ing ipsum dolor sit amet, consectetur dolor sit amet, consectetur adipisc ing ipsum dolor sit amet, consectetur elit.",
    imageUrl: require("../../images/review/8.jpg"),
    imageAlt: "1",
    tag1: "#new",
    tag2: "#game",
    tag3: "#adventure",
  },
  {
    id: Math.random(),
    title: "Susce pulvinar metus nulla, vel facilisis sem",
    desc:
      "Lorem ipsum dolor sit amet, consectetur adipisc ing ipsum dolor sit amet, consectetur dolor sit amet, consectetur adipisc ing ipsum dolor sit amet, consectetur elit.",
    imageUrl: require("../../images/review/9.jpg"),
    imageAlt: "1",
    tag1: "#new",
    tag2: "#game",
    tag3: "#adventure",
  },
  {
    id: Math.random(),
    title: "Susce pulvinar metus nulla, vel facilisis sem",
    desc:
      "Lorem ipsum dolor sit amet, consectetur adipisc ing ipsum dolor sit amet, consectetur dolor sit amet, consectetur adipisc ing ipsum dolor sit amet, consectetur elit.",
    imageUrl: require("../../images/review/10.jpg"),
    imageAlt: "1",
    tag1: "#new",
    tag2: "#game",
    tag3: "#adventure",
  },
  {
    id: Math.random(),
    title: "Susce pulvinar metus nulla, vel facilisis sem",
    desc:
      "Lorem ipsum dolor sit amet, consectetur adipisc ing ipsum dolor sit amet, consectetur dolor sit amet, consectetur adipisc ing ipsum dolor sit amet, consectetur elit.",
    imageUrl: require("../../images/review/10.jpg"),
    imageAlt: "1",
    tag1: "#new",
    tag2: "#game",
    tag3: "#adventure",
  },
  {
    id: Math.random(),
    title: "Susce pulvinar metus nulla, vel facilisis sem",
    desc:
      "Lorem ipsum dolor sit amet, consectetur adipisc ing ipsum dolor sit amet, consectetur dolor sit amet, consectetur adipisc ing ipsum dolor sit amet, consectetur elit.",
    imageUrl: require("../../images/review/9.jpg"),
    imageAlt: "1",
    tag1: "#new",
    tag2: "#game",
    tag3: "#adventure",
  },
  {
    id: Math.random(),
    title: "Susce pulvinar metus nulla, vel facilisis sem",
    desc:
      "Lorem ipsum dolor sit amet, consectetur adipisc ing ipsum dolor sit amet, consectetur dolor sit amet, consectetur adipisc ing ipsum dolor sit amet, consectetur elit.",
    imageUrl: require("../../images/review/8.jpg"),
    imageAlt: "1",
    tag1: "#new",
    tag2: "#game",
    tag3: "#adventure",
  },
  {
    id: Math.random(),
    title: "Susce pulvinar metus nulla, vel facilisis sem",
    desc:
      "Lorem ipsum dolor sit amet, consectetur adipisc ing ipsum dolor sit amet, consectetur dolor sit amet, consectetur adipisc ing ipsum dolor sit amet, consectetur elit.",
    imageUrl: require("../../images/review/7.jpg"),
    imageAlt: "1",
    tag1: "#new",
    tag2: "#game",
    tag3: "#adventure",
  },
  {
    id: Math.random(),
    title: "Susce pulvinar metus nulla, vel facilisis sem",
    desc:
      "Lorem ipsum dolor sit amet, consectetur adipisc ing ipsum dolor sit amet, consectetur dolor sit amet, consectetur adipisc ing ipsum dolor sit amet, consectetur elit.",
    imageUrl: require("../../images/review/6.jpg"),
    imageAlt: "1",
    tag1: "#new",
    tag2: "#game",
    tag3: "#adventure",
  },
  {
    id: Math.random(),
    title: "Susce pulvinar metus nulla, vel facilisis sem",
    desc:
      "Lorem ipsum dolor sit amet, consectetur adipisc ing ipsum dolor sit amet, consectetur dolor sit amet, consectetur adipisc ing ipsum dolor sit amet, consectetur elit.",
    imageUrl: require("../../images/review/5.jpg"),
    imageAlt: "1",
    tag1: "#new",
    tag2: "#game",
    tag3: "#adventure",
  },
  {
    id: Math.random(),
    title: "Susce pulvinar metus nulla, vel facilisis sem",
    desc:
      "Lorem ipsum dolor sit amet, consectetur adipisc ing ipsum dolor sit amet, consectetur dolor sit amet, consectetur adipisc ing ipsum dolor sit amet, consectetur elit.",
    imageUrl: require("../../images/review/5.jpg"),
    imageAlt: "1",
    tag1: "#new",
    tag2: "#game",
    tag3: "#adventure",
  },
  {
    id: Math.random(),
    title: "Susce pulvinar metus nulla, vel facilisis sem",
    desc:
      "Lorem ipsum dolor sit amet, consectetur adipisc ing ipsum dolor sit amet, consectetur dolor sit amet, consectetur adipisc ing ipsum dolor sit amet, consectetur elit.",
    imageUrl: require("../../images/review/6.jpg"),
    imageAlt: "1",
    tag1: "#new",
    tag2: "#game",
    tag3: "#adventure",
  },
  {
    id: Math.random(),
    title: "Susce pulvinar metus nulla, vel facilisis sem",
    desc:
      "Lorem ipsum dolor sit amet, consectetur adipisc ing ipsum dolor sit amet, consectetur dolor sit amet, consectetur adipisc ing ipsum dolor sit amet, consectetur elit.",
    imageUrl: require("../../images/review/7.jpg"),
    imageAlt: "1",
    tag1: "#new",
    tag2: "#game",
    tag3: "#adventure",
  },
  {
    id: Math.random(),
    title: "Susce pulvinar metus nulla, vel facilisis sem",
    desc:
      "Lorem ipsum dolor sit amet, consectetur adipisc ing ipsum dolor sit amet, consectetur dolor sit amet, consectetur adipisc ing ipsum dolor sit amet, consectetur elit.",
    imageUrl: require("../../images/review/8.jpg"),
    imageAlt: "1",
    tag1: "#new",
    tag2: "#game",
    tag3: "#adventure",
  },
  {
    id: Math.random(),
    title: "Susce pulvinar metus nulla, vel facilisis sem",
    desc:
      "Lorem ipsum dolor sit amet, consectetur adipisc ing ipsum dolor sit amet, consectetur dolor sit amet, consectetur adipisc ing ipsum dolor sit amet, consectetur elit.",
    imageUrl: require("../../images/review/9.jpg"),
    imageAlt: "1",
    tag1: "#new",
    tag2: "#game",
    tag3: "#adventure",
  },
  {
    id: Math.random(),
    title: "Susce pulvinar metus nulla, vel facilisis sem",
    desc:
      "Lorem ipsum dolor sit amet, consectetur adipisc ing ipsum dolor sit amet, consectetur dolor sit amet, consectetur adipisc ing ipsum dolor sit amet, consectetur elit.",
    imageUrl: require("../../images/review/10.jpg"),
    imageAlt: "1",
    tag1: "#new",
    tag2: "#game",
    tag3: "#adventure",
  },
  {
    id: Math.random(),
    title: "Susce pulvinar metus nulla, vel facilisis sem",
    desc:
      "Lorem ipsum dolor sit amet, consectetur adipisc ing ipsum dolor sit amet, consectetur dolor sit amet, consectetur adipisc ing ipsum dolor sit amet, consectetur elit.",
    imageUrl: require("../../images/review/10.jpg"),
    imageAlt: "1",
    tag1: "#new",
    tag2: "#game",
    tag3: "#adventure",
  },
  {
    id: Math.random(),
    title: "Susce pulvinar metus nulla, vel facilisis sem",
    desc:
      "Lorem ipsum dolor sit amet, consectetur adipisc ing ipsum dolor sit amet, consectetur dolor sit amet, consectetur adipisc ing ipsum dolor sit amet, consectetur elit.",
    imageUrl: require("../../images/review/9.jpg"),
    imageAlt: "1",
    tag1: "#new",
    tag2: "#game",
    tag3: "#adventure",
  },
  {
    id: Math.random(),
    title: "Susce pulvinar metus nulla, vel facilisis sem",
    desc:
      "Lorem ipsum dolor sit amet, consectetur adipisc ing ipsum dolor sit amet, consectetur dolor sit amet, consectetur adipisc ing ipsum dolor sit amet, consectetur elit.",
    imageUrl: require("../../images/review/8.jpg"),
    imageAlt: "1",
    tag1: "#new",
    tag2: "#game",
    tag3: "#adventure",
  },
  {
    id: Math.random(),
    title: "Susce pulvinar metus nulla, vel facilisis sem",
    desc:
      "Lorem ipsum dolor sit amet, consectetur adipisc ing ipsum dolor sit amet, consectetur dolor sit amet, consectetur adipisc ing ipsum dolor sit amet, consectetur elit.",
    imageUrl: require("../../images/review/7.jpg"),
    imageAlt: "1",
    tag1: "#new",
    tag2: "#game",
    tag3: "#adventure",
  },
  {
    id: Math.random(),
    title: "Susce pulvinar metus nulla, vel facilisis sem",
    desc:
      "Lorem ipsum dolor sit amet, consectetur adipisc ing ipsum dolor sit amet, consectetur dolor sit amet, consectetur adipisc ing ipsum dolor sit amet, consectetur elit.",
    imageUrl: require("../../images/review/6.jpg"),
    imageAlt: "1",
    tag1: "#new",
    tag2: "#game",
    tag3: "#adventure",
  },
  {
    id: Math.random(),
    title: "Susce pulvinar metus nulla, vel facilisis sem",
    desc:
      "Lorem ipsum dolor sit amet, consectetur adipisc ing ipsum dolor sit amet, consectetur dolor sit amet, consectetur adipisc ing ipsum dolor sit amet, consectetur elit.",
    imageUrl: require("../../images/review/5.jpg"),
    imageAlt: "1",
    tag1: "#new",
    tag2: "#game",
    tag3: "#adventure",
  },
]
